image: node:latest

stages:
    - staging
    - production

staging:
    type: deploy
    environment:
      name: staging
    stage: staging
    script:
        - npm i
        # your build command
        - CI=false npm run build
        - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
    only:
        - develop

production:
    type: deploy
    environment:
      name: production
    stage: production
    script:
        - npm i
        # your build command
        - CI=false npm run build
        - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
    only:
        - master